---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Site Data
- type: document
  path: content/pages/general.json
  label: General
  match: "**/*"
- type: heading
  label: Content
- type: directory
  path: content/blog
  label: Blog
  create: all
  match: "**/*"
  new_doc_ext: ".md"
- type: directory
  path: md
  label: Pages
  create: documents
  match: "**/*"
  exclude: general.json
  new_doc_ext: ".json"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
